### ISSUE TITLE
mypy-plugins

### ISSUE THREAD

**Issue by pmav99** [pre-commit/mirrors-mypy#9]
I want to enable  the pydantic-mypy plugin and use it from within pre-commit. The problem is that even though running mypy manually works, pre-commit fails

## Setup

All the packages are installed in the same virtual environment:
```
pip freeze | ag 'pre-commit|mypy|pydantic'
mypy==0.740
mypy-extensions==0.4.3
pre-commit==1.20.0
pydantic==1.2
```
I tried both mypy 0.740 and 0.761

#### `setup.cfg`:

Copy pasted from the mypy-pydantic docs:

```
[mypy]
plugins = pydantic.mypy

follow_imports = silent
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
check_untyped_defs = True

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True
```
#### `.pre-commit-config.yaml`:
``` yaml
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'master'
    hooks:
      - id: 'mypy'
```
#### Tracebacks

Running mypy directly succeeds (yes, there are errors, but mypy runs)
```
$ mypy rsutils
rsutils/sentinel/safe_validator.py:19: error: Name 'Parent' is not defined
rsutils/sentinel/__init__.py:1: error: Need type annotation for '__all__' (hint: "__all__: List[<type>] = ...")
rsutils/sentinel/__init__.py:5: error: Name 'safe_validator' is not defined
Found 3 errors in 2 files (checked 3 source files)
```
but calling pre-commit fails:
```
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Failed
hookid: mypy

setup.cfg:27: error: Error importing plugin 'pydantic.mypy': No module named 'pydantic'
Found 1 error in 1 file (checked 5 source files)
```

**Comment by asottile** [comment]
you're looking for [`additional_dependencies`](https://pre-commit.com/#pre-commit-configyaml---hooks)

**Comment by pmav99** [comment]
Thank you Anthony. 

For the record, the current version of pydantic-mypy seems to be incompatible with mypy 0.760. But it works with 0.740. The new version should be released shortly.  Until then, this config seems to be working:

```
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: 'v0.740'
    hooks:
      - id: 'mypy'
        args: []
        additional_dependencies:
          - 'pydantic'
```
